[package]
name = "decryption-server"
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = "2.0.0"
async-trait = "0.1.83"
bincode = "1.3.3"
ring = "0.17.8"
serde = "1.0.210"
serde_json = "1.0.128"
threshold_crypto = "0.4.0"
tokio = "1.40.0"
