services:
  counselify-backend:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile
    container_name: counselify-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - EXAMPLE_MESSAGE=Hello World!
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthz || exit 1"]
      interval: 2m
      timeout: 20s
      retries: 5
      start_period: 1m
